### ISSUE TITLE
What do we call the major UI components?

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/cli#102]
In the Jupyter Book theme, there are 5 main UI components:

![image](https://user-images.githubusercontent.com/1839645/79510647-92cdde80-7ff2-11ea-848a-5889d98df5d0.png)

We should make sure that we have a consistent and clear naming for each of them. I don't think we have that right now so this might take some brainstorming. Here is roughly what we call each:

1. Sidebar (sometimes "left sidebar")
2. Topbar
3. Main content
4. Sidebar
5. Table of Contents (sometimes "right sidebar")

In particular you'll note we use the word "sidebar" a lot :-) maybe this is fine as long as we clarify each, e.g.:

1 navigation sidebar
4 content sidebar
5 toc sidebar

what do folks think?

**Comment by chrisjsewell** [comment]
Off the top of my head:

1. nav-bar
2. top-bar/link-bar
3. content
4. margin
5. toc-bar

**Comment by choldgraf** [comment]
Nice, I quite like margin, too bad that the directive in rst is called “sidebar”, but maybe as long as we document it clearly that wouldn’t be too confusing.

I’m also +1 on the left bar being nav bar, and the right one being toc bar. That’s actually what the html id names are as well, I believe.

**Comment by choldgraf** [comment]
I've made a first step at some light renaming in the sphinx-book-theme and jupyter book CLI docs, so we now call the left thing the "nav bar" and the white space in the content the "margin" 👍

**Comment by choldgraf** [comment]
closing this as I think we now have more standard vocabulary
