### ISSUE TITLE
Trouble installing the CLI from OSX

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/cli#120]
Recently a colleague had issues getting the command line be accessible. After pip-installing, `jupyter-book` was not recognized at the command line, even though `import jupyter_book` worked fine.

I wonder if anybody in the EBP is using mac and can confirm that it has worked for them. @mmcky @jstac @chrisjsewell @AakashGfude do any of you use macs?

**Comment by choldgraf** [comment]
Note: I added a test for OSX just to be sure https://github.com/ExecutableBookProject/cli/pull/121

**Comment by phaustin** [comment]
Can confirm it works for me with this environment.yml:
https://github.com/eoas-ubc/eoas_tlef/blob/master/environment.yml

**Comment by andrewsanchez** [comment]
I didn't have any trouble installing the cli on my macbook.

**Comment by choldgraf** [comment]
I'm gonna close this since we now have a few people saying they were able to install from the CLI, and we also now have a test that builds with OSX
