### ISSUE TITLE
Theme issue when compiling docs

### ISSUE THREAD

**Issue by AakashGfude** [ExecutableBookProject/cli#128]
When I run `jupyter-book build docs/` I get the following error :- 

![image](https://user-images.githubusercontent.com/6542997/80334181-c979e380-8893-11ea-841d-7fd63708c032.png)

**Comment by choldgraf** [comment]
Looks like you don't have the sphinx book theme installed

**Comment by AakashGfude** [comment]
Thanks @choldgraf

**Comment by mmcky** [comment]
@choldgraf the theme should come packaged with the `cli` right?

**Comment by choldgraf** [comment]
Yep. But my guess is something went wonky with the dev installs
