### ISSUE TITLE
Discuss making the button backgrounds transparent

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/cli#129]
In a recent issue @jstac mentioned that the top-bar buttons are a bit "imposing" with the main text. We don't want these to distract from reading the main content itself.

One option would be to make the buttons "text only". AKA, not using a background that makes the button boundary obvious. Something like this:

![image](https://user-images.githubusercontent.com/1839645/80413787-d93dfb80-8884-11ea-8b51-2b106c5050fc.png)

What do people think about this idea? Would it be confusing to folks that these aren't buttons? Is there a way that we could suggest these are "clickable" without the full black background?

**Comment by chrisjsewell** [comment]
In terms of being out the way of the main header text:

1. Do you actually need the text, as opposed to just icons
2. Could the buttons be aligned to the right of the screen

**Comment by choldgraf** [comment]
interesting - I hadn't thought about right-aligning...here's what it would look like:

![image](https://user-images.githubusercontent.com/1839645/80414650-371f1300-8886-11ea-8ad3-2661930223f4.png)

for the text - we currently hide the text when the screen reaches a certain narrowness. Though agree maybe it is redundant? We could just have it show the text on hover

**Comment by choldgraf** [comment]
I have a demo for the transparent backgrounds and text here: https://github.com/ExecutableBookProject/sphinx-book-theme/pull/78

what do folks think?

**Comment by chrisjsewell** [comment]
FYI here's how it currently looks on my screen (Mac OS, 2560 x 1440 monitor, and I use the https://darkreader.org/ firefox extension)

![image](https://user-images.githubusercontent.com/2997570/80439471-843ecb80-88fe-11ea-8849-331d30fc86f2.png)

Looks good, but some nitpicks

1. Yeh I think the buttons on the right might be even better
2. The full screen button is slightly bigger than the others
3. The tooltip for the download/launch buttons gets in the way of the drop-down menu
4. Would be nice if the logo background was transparent
5. Might be nice if the core content expanded to fit the screen
6. Something slightly different to Fullscreen is "Zen/Reading Mode", which involves potentially going into fullscreen, but also stripping away all the panels except the core content. Not sure if this is possible with HTML5?

**Comment by chrisjsewell** [comment]
The VS Code documentation theme is maybe a bit nicer, in how it has a clearly color delimited banner, which makes it look a little less "messy" at the top:

![image](https://user-images.githubusercontent.com/2997570/80441115-214f3380-8902-11ea-8a4b-4d347f48c5b9.png)

**Comment by choldgraf** [comment]
good catch on all of those - I'll try to fix the easy ones tomorrow. The other stuff we might need to have on the backburner for long-term improvements

**Comment by chrisjsewell** [comment]
Another theme for comparison is the [Docker documentation](https://docs.docker.com/compose/django/):

![image](https://user-images.githubusercontent.com/2997570/80442553-0df19780-8905-11ea-9b04-5d630fa2090f.png)

This also has the banner at the top, but also pushes the side bars out to the extents, and interestingly has a togglable light-to-dark mode buttton on the right

**Comment by choldgraf** [comment]
while we're at it, here's another that I've been using for inspiration from the Metaflow docs:

![image](https://user-images.githubusercontent.com/1839645/80443353-df070180-88c3-11ea-9a15-e655093f5374.png)

**Comment by jstac** [comment]
I like the Metaflow example.  It's clean and relatively low key, which seems good for us.

Where they say "contents" on the top right, a better choice for us would be "On this page" or similar --- so as not to generate confusion with the TOC.

**Comment by choldgraf** [comment]
one step ahead of you :-)

![image](https://user-images.githubusercontent.com/1839645/80444361-6e151900-88c6-11ea-845d-548aa0104111.png)

**Comment by jstac** [comment]
Nice!

**Comment by choldgraf** [comment]
check out https://github.com/ExecutableBookProject/sphinx-book-theme/pull/79

a few other points worth mentioning:

* for the logo background, definitely agree. this should be fixed when we have a standardized set of logos etc
* for expanding the content to fit the screen, in pydata-sphinx-theme we intentionally cap the width of the content so it doesn't get too wide, trying to follow web best practices for content with for reading...we can discuss if this needs to be adjusted a bit
* for "focus" mode, it's a bit tricky to get *just* the content to expand, but it is doable. Might require refactoring the CSS though, so let's leave it to the future if it's an important feature to have

**Comment by choldgraf** [comment]
closing this one since we now have transparent and right-aligned buttons! we can open new issues (in `jupyter-book` now!) for new things to tackle
