### ISSUE TITLE
shorter name for binary?

### ISSUE THREAD

**Issue by jstac** [ExecutableBookProject/cli#25]
How about `jbk` instead of `jupyter-book` when invoking the CLI?

Obviously there are pros and cons, but "jupyter-book" is kind of hard to type, even with tab expansion.

(And yes, I know I can make an alias, before you point that out :-)

**Comment by choldgraf** [comment]
It's not documented, but I actually also make just "jb" available for the binary too. I agree w you... Maybe jb is too non-specific though?

**Comment by jstac** [comment]
Ah, no, `jb` is perfect.  I didn't realized it was free.  (Typed it, saw something come up, didn't look closely, figured another program was using it :sweat_smile: )

I suggest we note it in the docs, somewhere prominent ("Alternatively, you can use `jb build xxx`")
