### ISSUE TITLE
align not working in docs

### ISSUE THREAD

**Issue by jstac** [ExecutableBookProject/cli#26]
On https://beta.jupyterbook.org/features/markdown.html I'm seeing an align environ that's not working:

![Screenshot_2020-03-08_16-38-02](https://user-images.githubusercontent.com/3887684/76157319-54274780-615b-11ea-8269-75f7eb169e3f.png)

Also, what kind of monster fails to nicely indent their LaTeX source?

I'll fix it for you.

**Comment by choldgraf** [comment]
Lol anything resembling latex is 100% copypasta from the internet, I would love to see improvements in the mathematics on the docs! 😊

**Comment by choldgraf** [comment]
@jstac do align environments now work for you?

**Comment by jstac** [comment]
Yep, looking good.  I tidied up the LaTeX code here: https://github.com/ExecutableBookProject/cli/pull/106
