### ISSUE TITLE
Clarify how page titles are determined

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/cli#37]
Here are the rules from Jupyter Book:

https://beta.jupyterbook.org/old_docs/features/titles.html

we could start off by mimicking this and then extend from there

One catch here is that we would need to make sure the title makes it into the `doctree` somehow, because otherwise Sphinx won't be happy. If we read in a page that didn't have a title in the markdown header, we'd need to reference the page in the TOC and then insert the title into it.

This might be easier if we did the TocTree stuff in a [`doctree-read` event](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-doctree-read) rather than a source-read event, so we could manually update the doctree title node.

**Comment by najuzilu** [comment]
If possible, we should provide an example for each.

For instance,  I understood this:
> A `title:` field for this entry in the book’s Table of Contents file (`toc.yml`)

to be something like this
```
- file: source/index_learning_python
  pages:
    - file: source/about_py
      title: Test 
```
But I don't see it rendered on `HTML` so I might have misunderstood.

**Comment by choldgraf** [comment]
Ahh - I think that's a bug in there, I'll make a PR update to the docs soon and let's see if that fixes it

**Comment by choldgraf** [comment]
Check out the new docs page, and see if that works! https://beta.jupyterbook.org/features/toc.html#custom-page-titles

**Comment by najuzilu** [comment]
Nice work on the documentation @choldgraf! Unfortunately, the changed title is not picked up from the ToC file. I even tried commenting out the heading in the main markdown file and did not get anywhere...

**Comment by choldgraf** [comment]
@najuzilu did you update to the latest master as well? there was also a bugfix in there...

**Comment by najuzilu** [comment]
Nice job @choldgraf !! I `pip uninstalled` and `installed` again and it worked great! It is only supposed to change the title on the navbar correct?

I'd like to add pre and post title example pictures in the documentation. Do you think that's something that is useful? I think people skim by looking at examples/output and then read the documentation (at least I do :-D).

**Comment by choldgraf** [comment]
could you give me an example of what you mean by  pre- and post-?

**Comment by najuzilu** [comment]
Prior to adding the title key in ToC:
<img width="249" alt="Screen Shot 2020-03-26 at 4 39 30 PM" src="https://user-images.githubusercontent.com/33075058/77614171-a56b6f80-6f80-11ea-9c8c-db5d307ae17d.png">

Post adding `title: Python 101` to ToC file:
<img width="277" alt="Screen Shot 2020-03-26 at 4 42 14 PM" src="https://user-images.githubusercontent.com/33075058/77614261-cfbd2d00-6f80-11ea-8d8d-899ddf73cb27.png">

**Comment by choldgraf** [comment]
Hmm - do you think it isn't clear what will be changed when people tweak this option? If you think this would clear it up, I'd be +1 on it - though we should make sure the image files are as small as possibel

**Comment by najuzilu** [comment]
It was my understanding reading the documentation that including `title` would also display the changed title on the `html` page in addition to the `navbar` and `sidebar`. Since this is not the case (is this a bug?), maybe we should specify this behavior in the documentation. Hence, my suggestion for including images.

**Comment by choldgraf** [comment]
Makes sense - in this case, it's not a bug...we might be able to control the display of the actual title but it'd require changing the Sphinx HTMLBuilder, so I'd like to put that off until later if possible.

**Comment by choldgraf** [comment]
I think this is now fixed
