### ISSUE TITLE
Ignore files not specified in toc during build

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/cli#45]
@choldgraf is it possible to ignore files which have not been specified in `_toc.yml` when building? I keep getting this error:

`FileNotFoundError: The following path in your table of contents couldn't be found:`

**Comment by choldgraf** [comment]
Hmmm - well this is intended behavior, because I'm assuming that the user wants to show *everything* that's a content file in the Table of Contents...however, perhaps this could be a config.yml key that lets people specify paths to files that will be excluded from the build...

**Comment by najuzilu** [comment]
I would find it useful - at least while I'm testing. I wonder what others think about this tho...

**Comment by jstac** [comment]
Yes, it might be useful --- we sometimes have half-finished lectures that we don't want in the final build.  Although my solution in that case is to keep them in a separate branch, where I'm going to add them to the TOC or I'm not be concerned about the error.  Perhaps that's good enough for your case too @najuzilu ?

Although now I read your question at the top again, @najuzilu, and the error message, I wonder if @choldgraf and I have understood correctly.  Your error message suggests that you have a path in the TOC but no corresponding file in the repo --- is that right?

 If that's true can you just comment it out?

**Comment by najuzilu** [comment]
The error is confusing - it should probably provide a different error message. I have a file in the directory which is not mentioned in the TOC. When I try to build, it produces that error.

**Comment by jstac** [comment]
OK, then the message is confusing, as you say.  But @choldgraf has understood it correctly.

I guess you could try putting together a PR that improves the error message and, if @choldgraf agrees, that allows for ignores to be specified in the conf file.  But maybe that's a task for next week?

**Comment by najuzilu** [comment]
I would expect the following behavior in these two scenarios:

1. If file not referenced in TOC, a warning should be displayed that file is not referenced in TOC. There should exist a `config.yml` key i.e. `exclude` to exclude these files during build and therefore no warnings should appear if such key is specified. **Currently**, the build displays this exception and will not build the rest of the files. I would expect it to display a warning but continue to process the rest of the files.

2. If file referenced in TOC but file not found. This should definitely throw an exception and terminate the build. **Currently** it just displays a warning.

I think the current behavior should be flipped. Would like to know your thoughts @choldgraf @jstac

**Comment by jstac** [comment]
I agree with both suggestions.

**Comment by choldgraf** [comment]
so do I!

**Comment by najuzilu** [comment]
Great. I'll try to look into this more specifically some time next week as @jstac suggested.

**Comment by trallard** [comment]
Hey just jumping in here! Having the ability to exclude some notebooks (either through a `exclude` flag in the config file would be great!

**Comment by choldgraf** [comment]
hey all - thanks for the feedback! I think that I've fixed this up in https://github.com/ExecutableBookProject/cli/pull/70

We still need to find a good way to document the `_config.yml` file...
