### ISSUE TITLE
File header displayed under navbar

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/cli#46]
All the headers for the lectures are currently displayed under the navbar. Is there a quick fix for this i.e. in the page’s metadata? The files I have built are `*.md` where the first line is a H1 header.

<img width="1425" alt="Screen Shot 2020-03-25 at 3 52 58 PM" src="https://user-images.githubusercontent.com/33075058/77535536-d8fdb980-6eee-11ea-9be2-bb1dbacb32ff.png">

**Comment by choldgraf** [comment]
Hmmm - is this true for all headers, or just ones where there is very little content on the page? Can you give a link to a page that has the issue?

**Comment by najuzilu** [comment]
This is true for all headers in all files. I have the underlying project [here](https://github.com/ExecutableBookProject/quantecon-example/tree/add-files). The `md` files are under `source` but you'll have to build it to access `html`.

**Comment by najuzilu** [comment]
I'll close this since the problem was that I was using an older version of `sphinx-book-theme`.
