### ISSUE TITLE
Error: No such command "toc"

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/cli#47]
Following the documentation, I tried `jupyter-book toc mybookcontent/` and got this message:
`Error: No such command "toc"`

I only see the following commands:
<img width="529" alt="Screen Shot 2020-03-26 at 11 31 12 AM" src="https://user-images.githubusercontent.com/33075058/77598216-552ae800-6f55-11ea-8ad5-6d0f6ace8d13.png">

**Comment by choldgraf** [comment]
hmmm - that is weird...can you try making sure you are on the latest master branch? You should get the following when calling `--help`:

```
jupyter-book --help
Usage: jupyter-book [OPTIONS] COMMAND [ARGS]...

  Build and manage books with Jupyter.

Options:
  --help  Show this message and exit.

Commands:
  build   Convert a collection of Jupyter Notebooks into HTML suitable for
          a...

  create  Create a simple Jupyter Book that you can customize.
  page    Convert a single notebook page to HTML or PDF.
  toc     Generate a _toc.yml file for your content folder (and...
```

**Comment by najuzilu** [comment]
Upgrading fixed these! Thanks @choldgraf
