### ISSUE TITLE
html_logo margins in navbar

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/cli#50]
Is there a way to fix these margins? Or is it occurring because my `html_logo` reference is not square?

<img width="1425" alt="Screen Shot 2020-03-26 at 3 31 47 PM" src="https://user-images.githubusercontent.com/33075058/77610569-2e7da900-6f77-11ea-90e2-26a740131072.png">

**Comment by choldgraf** [comment]
hmmm - this makes me wonder if you are also on an older version of the `sphinx-book-theme`? Try updating that to the latest version as well

**Comment by najuzilu** [comment]
Wouldn't `pip install` get the latest version of `sphinx-book-theme`?

**Comment by choldgraf** [comment]
Nope, it's not uploaded to pip yet, the latest version is on github only, so you may need to do a git clone, followed by 'pip install - e'

**Comment by najuzilu** [comment]
It worked! Thanks @choldgraf!
