### ISSUE TITLE
Update title in sidebar to match title in config

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/cli#52]
Is there a way to update the title in the sidebar to match the title in config? It currently shows up as "My Jupyter Book documentation".

**Comment by choldgraf** [comment]
I don't think that's possible yet, I haven't adapted over the config from "old jupyterbook config" to new one...but I can get this done tomorrow 👍

**Comment by choldgraf** [comment]
This is now fixed!

**Comment by najuzilu** [comment]
Should this also fix the title on the actual page as well? Or we're not there yet?

**Comment by choldgraf** [comment]
As in each page title? I think that will remain as whatever is written in the page for a while, it's more complex to fix :-/
