### ISSUE TITLE
Header and divider keys not rendering

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/cli#56]
I can't seem to get `header` and `divider` keys in ToC to display on either the static HTML or published book ([see here](https://executablebookproject.github.io/quantecon-example/docs/index_python_scientific_libraries.html)). Any suggestions as to how to fix this?

**Comment by choldgraf** [comment]
Is this still an issue after the other bugfixes that we'v worked on the last few days?

Also I suspect that we'll change the way that the TOC handles headers and such, so perhaps we can put a pin in this issue until those changes come in?

**Comment by najuzilu** [comment]
I just updated my env and still don't see `header` and `divider` displayed. Sure, let's put a pin in this issue until we've finalized the way the TOC handles them.

**Comment by choldgraf** [comment]
this is now fixed
