### ISSUE TITLE
Option to download file as ipynb, md and pdf

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/cli#59]
Will we be able to download a file in all three formats? I was thinking something along these lines: if the directory where the local files have the same name but different extension, they should be downloadable.

**Comment by choldgraf** [comment]
Right now - you have two options: PDF, or the original file format. I think in the future we might want to add the ability to download an `ipynb` file if the file is a "notebook-in-markdown" file...but for now it's just source and PDF

**Comment by chrisjsewell** [comment]
The text-based notebooks, similar to regular notebooks, are saved in `_build/jupyter_execute` as `.ipynb` and `.py`, and so should be able to assessed in the same way, e.g. with https://jupyter-sphinx.readthedocs.io/en/latest/#downloading-the-code-as-a-script

**Comment by choldgraf** [comment]
that's awesome - so we could keep both artifacts in the page and allow people to download either. I think that could be a nice way to highlight to people the dual-nature of myst-nb / ipynb files

**Comment by chrisjsewell** [comment]
What do you think about this, I've added them as footnote: https://309-241268229-gh.circle-artifacts.com/0/html/use/basic.html#download. Or should/could this be done in a more global/automated fashion. For example, nbsphinx adds a prolog to pages: https://nbsphinx.readthedocs.io/en/0.5.1/subdir/a-notebook-in-a-subdir.html, but that takes up quite a bit of real estate at the start of the page, which I don't think you would want for books.
Also, I guess you might only want these added for HTML outputs, not LaTeX/PDF

**Comment by choldgraf** [comment]
What I've done so far is add them as collapsible "download" buttons on each page in the `sphinx-book-theme`: 

![image](https://user-images.githubusercontent.com/1839645/78089147-56a44800-737b-11ea-990c-7c2d57544994.png)

e.g.: https://beta.jupyterbook.org/use/notebooks.html

**Comment by chrisjsewell** [comment]
How can we integrate that into the myst-nb documentation? Does it need to move at some point to this theme?

**Comment by choldgraf** [comment]
Right now it is hard-coded into the theme, yeah. But it shouldn't be that hard to have those buttons as a directive, or something like this. Maybe that's something we could move into myst-nb, and then the book theme could just use a myst-nb function to build the buttons

**Comment by choldgraf** [comment]
(though either way, I'd be +1 on moving most of our documentation to the book theme, just so we are consistent in the styles etc that we're using, and to dog-food our own theme a bit)

**Comment by choldgraf** [comment]
this is now fixed w/ changes in sphinx-book-theme
