### ISSUE TITLE
Build command ignores `--no-execute`

### ISSUE THREAD

**Issue by jonasdaugalas** [ExecutableBookProject/cli#63]
Not sure if I am using it correctly, but seems that `build` command accepts `--execute/--no-execute` flag, which is never used in the command handler
https://github.com/ExecutableBookProject/cli/blob/master/jupyter_book/commands/__init__.py#L25

Is this intended?

**Comment by choldgraf** [comment]
Hmmm - it should be passed through as a configuration value: https://github.com/ExecutableBookProject/cli/blob/master/jupyter_book/commands/__init__.py#L99

lemme look into it

**Comment by choldgraf** [comment]
oops you're right, I think it was added to `page` but not to `build`

**Comment by choldgraf** [comment]
I think it was a mistake that we added in that CLI option - for controlling execution of whole books, try following these instructions: https://beta.jupyterbook.org/use/execute.html#execute-and-cache-your-notebooks

we'll keep `--execute` just for the single page case for now

**Comment by jonasdaugalas** [comment]
Got it. Instructions make it clear. I just found it by `jupyter-book build --help`.

**Comment by choldgraf** [comment]
yep - I just removed that in #65 :-)

**Comment by choldgraf** [comment]
should now be fixed as we use the `config` file for execution
