### ISSUE TITLE
Display error from execution of code-block in output cell

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/cli#67]
I can't seem to get past build if I want to display the actual execution error in the book. I didn't see a directive option for this in the documentation. Is this currently possible?

<img width="670" alt="Screen Shot 2020-03-31 at 5 52 26 PM" src="https://user-images.githubusercontent.com/33075058/77996056-a5041780-7378-11ea-8263-10db14914860.png">

**Comment by chrisjsewell** [comment]
You have to tag the cell with `raises-exception`

**Comment by chrisjsewell** [comment]
That’s if you are using an actual notebook, as opposed to the jupyter-sphinx directives. But note these directives will probably soon be ‘obsolete’, in favour of using the myst notebook representation: https://jupytext.readthedocs.io/en/latest/formats.html#myst-markdown. This is not yet implemented in myst-nb, but hopefully soon

**Comment by najuzilu** [comment]
Yeah, I'm using jupyter-sphinx directives... thanks @chrisjsewell

**Comment by chrisjsewell** [comment]
Yeh the jupyter-sphinx has a raises option: https://github.com/jupyter/jupyter-sphinx/blob/970097e01c1b7af04372be202aed572de68d2d20/jupyter_sphinx/ast.py#L50

**Comment by najuzilu** [comment]
This is exactly what I needed! We should add this in the documentation. :-D

**Comment by choldgraf** [comment]
@najuzilu in the future, we'll need to use a `raises-exception` tag for the cell (whether it's an `ipynb` file or ` myst-nb` markdown file). Agreed we should document this somewhere!

**Comment by chrisjsewell** [comment]
Way ahead of you: ExecutableBookProject/MyST-NB#116

https://306-241268229-gh.circle-artifacts.com/0/html/use/markdown.html

**Comment by choldgraf** [comment]
Big +1 for Simpsons references

**Comment by chrisjsewell** [comment]
Little Easter egg for ya 😂

**Comment by choldgraf** [comment]
I think this is now fixed
