### ISSUE TITLE
Move this repository into `jupyter-book` somehow?

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/cli#76]
The plan for this repository is to use it as a place to rapidly prototype a command-line interface that we will then move into the current jupyter-book repository (github.com/jupyter/jupyter-book).

At some point once we are happy with the CLI and ready to have it released as a "beta", we should move this over to a "beta" branch of the current jupyter book repo. This will be a pretty big switch, and basically entails totally swapping out one codebase for another since the backend is completely re-written. We might also want to create some pre-releases or "beta" releases for a time to let people use it and give feedback.

Does this seem like a reasonable approach to everybody? @jstac @mmcky @chrisjsewell what do you think?

**Comment by jstac** [comment]
Yes, it's a big switch, and hard on existing users, particularly if they're currently using jupyter-book for an ongoing lecture series.

That sounds like a good plan.  Might it be worth flagging the upcoming transition in a note here: https://jupyterbook.org/intro ?

**Comment by choldgraf** [comment]
@jstac that's a good idea. Once we are happy for "users we know" to try it out, I'll add a note to the introduction page w/ a link to the beta page

**Comment by mmcky** [comment]
@choldgraf I think it would be valuable to get current users to run a `beta` over their projects for bug identification (if they are willing to do so). I think we should give them plenty of time to test and report back.

I agree with @jstac -- its a big switch.

**Comment by choldgraf** [comment]
Yeah for sure - I'll put a big ol' "WARNING THINGS ARE GOING TO CAHNGE" on the jupyter book landing page :-)

**Comment by choldgraf** [comment]
done!
