### ISSUE TITLE
white space after lists

### ISSUE THREAD

**Issue by jstac** [ExecutableBookProject/cli#77]
These pages would look nicer with empty lines after lists:

https://executablebookproject.github.io/quantecon-example/docs/getting_started.html

For example, there should, IMO, be a blank line before "The best such distribution is Anaconda."

I guess this is bound up with the theme but do others agree, in any case?

CC @choldgraf @najuzilu, related to https://github.com/ExecutableBookProject/quantecon-example/issues/2

**Comment by mmcky** [comment]
I fully agree -- we should increase the padding around these types of objects in the theme.

**Comment by najuzilu** [comment]
@jstac, @mmcky: This is fixed.
<img width="779" alt="Screen Shot 2020-04-03 at 12 23 07 PM" src="https://user-images.githubusercontent.com/33075058/78314508-e2012180-75a5-11ea-8f2a-7e4b8cb79f44.png">

**Comment by jstac** [comment]
Great, thanks @najuzilu.  Can you tell me which PR?

(Or, more generally, was it fixed in the theme or in the md file or somewhere else?)

**Comment by choldgraf** [comment]
It was fixed in the theme!

**Comment by jstac** [comment]
Thanks guys, nice work :-)
