### ISSUE TITLE
WARNING: Found a content page that is not in Table of Content

### ISSUE THREAD

**Issue by AakashGfude** [ExecutableBookProject/cli#80]
As mentioned by @najuzilu , the present build of [quantecon-example](https://github.com/ExecutableBookProject/quantecon-example), is giving the following warnings 
![image](https://user-images.githubusercontent.com/6542997/78423407-d7cc4980-76b1-11ea-8ee9-ce524f863042.png)

which is caused by the `add_toctree` function in `toc.py`  of this repository.
![image](https://user-images.githubusercontent.com/6542997/78423507-7bb5f500-76b2-11ea-90a4-f17d21bf58cc.png)
The files mentioned in the warnings above are present in the `toc` variable but `find_name` function is not able to fin it.

Will create a PR fixing this issue.

**Comment by najuzilu** [comment]
It looks like we've moved away from `pages` and are now calling them `sections` hence the warnings. I'll update this in the repo so you can pull the latest. Thanks @AakashGfude
