### ISSUE TITLE
Help setting up codecov?

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/cli#86]
Hey @chrisjsewell - I am trying to professionalize the codebase a bit and add tests before a more public release. I'm trying to add codecov to the repository, but for some reason it seems like it isn't showing up in my codecov account.

Do you need to add me or something? And do you know of a good tutorial for where to make the "first commit" for the codecov to reference?

I got it working on the `jupyter-book` repo, so another option is that we just wait for codecov until we move this over there

**Comment by chrisjsewell** [comment]
I’ve added the repo here: https://github.com/organizations/ExecutableBookProject/settings/installations/7815813

**Comment by choldgraf** [comment]
nice - it works great (well, the actual codecov report numbers, not so much, but I'll get on that 😆
