### ISSUE TITLE
Best way to overwrite the Jupyter Book repository?

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/cli#87]
The CLI repository is effectively a completely different codebase from the current `jupyter-book` repository (which is great).

I am trying to figure out the "best" way to make the switch. We could make one gigantic commit where we delete all the old jupyter book, and replace it with the new jupyter book. However, then we are going to have a *ton* of extra files in the github history that will make the repository quite large. Is that an issue, or worth planning around? Or do folks think it's fine?

cc @chrisjsewell or @mmcky in case they have experience porting large codebases before

**Comment by chrisjsewell** [comment]
You can do this, with things like `got cherry-pick`. I’m a bit confused though why not just make this the “new” jupyter-book repository and deprecate the old one, why does everything have to be copied over?

**Comment by mmcky** [comment]
hey @choldgraf - is the issue here with naming of the repository? 

I tend to think the best way for this would be to as @chrisjsewell says to just `deprecate` the old repo and rename the current `cli` repo. Then update necessary links etc. This way you have a clear end point for the previous project (and any others could pick it up if they wanted to for some reason i.e. invested heavily in it and want to keep moving it forward for their own projects).

If its an issue with github names then I would rename the old project `jupyterbook.jekyll-v{}` or something like that.

**Comment by choldgraf** [comment]
to me the reason to keep that repository is a combination of:

1. GitHub repo history (issues, PRs, comments, etc)
2. git repo history (commits etc)
3. Avoiding confusion for users who are used to going to that repo (there are already a lot of links out there pointing to `jupyter/jupyter-book`

Mostly, I don't want to wipe out the contributions that others have given to the project, given that I am not the only who has written code for Jupyter Book. In addition, there are a lot of issues in there that are probably still relevant to whatever new build system

As a tactical point - I think there's also a value to having a repository under the `jupyter/` github org. It makes people treat it more seriously and has more immediate cred, and I don't think we want to give that up

**Comment by mmcky** [comment]
Hey @choldgraf in that case I would probably have one big commit announcing a new backend for the project coupled with the introduction of a new `markup` syntax `myst` etc. etc. (and a major version change :-)).

Have you sampled a number of previous projects? Will they continue to build without intervention?

**Comment by choldgraf** [comment]
I'm working with a few current jupyter book users to see what the migration looks like. The new build system isn't too different, there will just be some configuration changes etc, and the whole thing will be simpler. I just had a good chat with @martinagvilas who shared some of the challenges in upgrading, and I think we should make an "upgrading your book" section for current jupyter book users

**Comment by choldgraf** [comment]
Another idea that I had is that we could do the following:

* Move the current jupyter-book code to a `legacy` branch
* Add the CLI as a remote to the jupyter-book repo
* Run a `git reset --hard executablebookproject/master` from the jupyter-book repo
* Force-push to master on jupyter-book

That way, we have history preserved in the `legacy` branch, and we retain all of the issues etc that are currently in there (for which many could now be closed).

**Comment by chrisjsewell** [comment]
Yeh err I still think this is going to be a big hassle: we've got all these interdependent repositories within ExecutableBookProject, and now we are going to have the main user facing one in a completely different project. For example, we will have to scrap these new project boards https://github.com/orgs/ExecutableBookProject/projects, because they only work within the same project

> I think there's also a value to having a repository under the jupyter/ github org
> It makes people treat it more seriously and has more immediate credibility, and I don't think we want to give that up

This is the **only** reason I see as a legitimate justification for this. Sorry to the contributors of the original `jupyter-book` but this is a completely different code-base

**Comment by choldgraf** [comment]
> but this is a completely different code-base

I sort-of agree, but think it's more complex than that.

* From an UI/API perspective, it is nearly the same project
* From a designer's perspective, it is nearly the same project
* From a user's perspective, it is the same project
* From a developer's perspective, it is a different code base (but not necessarily a different project)

Or put another way, the reason that I opened up the CLI in this EBP org is because it would be easier to iterate rapidly as the tech was changing quite quickly. But I see it as a new major version of the project, not a "different" project (there's a reason it's called "Jupyter Book 2.0"). 

I agree with you that there is downside in having one repository that is not inside the EBP organization - but, I think the upside to having keeping the repository where it is is also considerable. Association with the `jupyter/` org is a pretty big benefit, not to mention the fact that it is already a "known" entity in the open source world and so we don't need to spend as much time convincing people to use it (much harder than building the tech in the first place, IMO). It'd also have continuation of momentum from the Jupyter Book dev community, and I think would make it easier to move that momentum into the broader EBP projects.

**Comment by choldgraf** [comment]
Hey all - after thinking about this a bit more and considering @chrisjsewell's thoughts, I am leaning towards the following and would like to know if people are +1

* Move the `jupyter-book` repository out of `jupyter/` and into `ExecutableBookProject/`
* Move the `jupyter-book` master to a `legacy` branch
* **Replace** via a force-push the CLI master to the Jupyter Book master
* Migrate over issues in CLI that make sense in Jupyter Book

That way, we can keep continuity in the Jupyter Book repo, and we get the benefit of having all of our repositories under the EBP project. I think there's some downside to not being inside the jupyter org, but I the upside that Chris mentioned about having all of the project repositories in one place will outweigh it

**Comment by choldgraf** [comment]
OK, I've got the jupyter-book repo in this github org now. Let's finish up @jstac and @mmcky 's PRs in this repo, and then we can transfer over the codebase to a `beta` branch and see how it goes. Let me know if folks have thoughts on that.

**Comment by chrisjsewell** [comment]
wahoo I win 😆 🏆 but joking aside, I'm +1 on your proposal

**Comment by choldgraf** [comment]
this is done!
