### ISSUE TITLE
Reference a figure by its number.

### ISSUE THREAD

**Issue by jstac** [ExecutableBookProject/cli#92]
After creating a figure with caption like

```{figure} some/path/fig.png
:name: a_name

A caption
```

the figure is published with a figure number and caption ("Fig. 1 A caption").  

How can we reference this number?  For example, how to produce:  "See Figure 1."

(An html link to the figure is easy to insert using the usual sphinx mechanism but this is not suitable for material that's likely to be printed.)

An explanation needs to be added to the docs.

**Comment by choldgraf** [comment]
Ah I found the docs we need to pull from:

https://www.sphinx-doc.org/en/1.5/markup/inline.html#role-numref

**Comment by jstac** [comment]
Thanks!  @najuzilu, can you work this into quantecon-mini-example?  For example, "Figure x shows a Jupyter notebook in action... blah blah".

**Comment by najuzilu** [comment]
@jstac this has been addressed [here](https://executablebookproject.github.io/quantecon-mini-example/docs/getting_started.html#jp-demo)

**Comment by jstac** [comment]
Thanks @najuzilu !
